### ISSUE TITLE
在8.0时崩溃

### ISSUE THREAD

**Issue by sanjin0211** [yangchaojiang/ZoomPreviewPicture#49]
在8.0手机上运行时Theme属性报错

**Comment by yangchaojiang** [comment]
你请问你，自定义activity么
方便错误日志接一下

**Comment by protectedMan** [comment]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.zl.lezhu/com.previewlibrary.GPreviewActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
3 ......
4 Caused by:
5 java.lang.IllegalStateException:Only fullscreen opaque activities can request orientation
6 android.app.Activity.onCreate(Activity.java:1081)
7 android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
8 android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:321)
9 com.previewlibrary.GPreviewActivity.onCreate(GPreviewActivity.java:54)
10 android.app.Activity.performCreate(Activity.java:7372)
11 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
12 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
13 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
14 android.app.ActivityThread.-wrap12(Unknown Source:0)
15 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
16 android.os.Handler.dispatchMessage(Handler.java:108)
17 android.os.Looper.loop(Looper.java:166)
18 android.app.ActivityThread.main(ActivityThread.java:7425)
19 java.lang.reflect.Method.invoke(Native Method)
20 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
21 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

 8.0崩溃

**Comment by yangchaojiang** [comment]
试一下2.1.3
